import os
import sys
import io
import time
from contextlib import redirect_stdout, redirect_stderr

# Ensure we run in correct directory
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

def run_suite_and_generate_report():
    import pytest

    print("Running Project Zenith unit test suite...")

    # We will capture stdout/stderr from pytest execution
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()

    start_time = time.time()
    
    # Run pytest programmatically
    # We pass the paths to the tests directly
    test_args = ["-v", "--tb=short", "tests/"]
    
    with redirect_stdout(stdout_buf), redirect_stderr(stderr_buf):
        exit_code = pytest.main(test_args)
        
    duration = time.time() - start_time

    pytest_output = stdout_buf.getvalue()
    pytest_errors = stderr_buf.getvalue()

    # Determine status
    if exit_code == 0:
        status_banner = "🟢 ALL TESTS PASSED"
        status_desc = "All unit and integration tests executed successfully."
    else:
        status_banner = "🔴 TESTS FAILED"
        status_desc = f"Pytest exited with non-zero code: {exit_code}. Some tests failed."

    # Parse pytest output for counts
    # E.g. "7 passed, 1 warning in 4.12s"
    summary_line = ""
    for line in pytest_output.splitlines():
        if "====" in line and ("passed" in line or "failed" in line or "error" in line):
            summary_line = line.strip(" =")
            break

    errors_section = ""
    if pytest_errors.strip():
        errors_section = f"### ⚠️ Errors / Stderr Output\n```text\n{pytest_errors}\n```"

    # Build the report markdown
    report_content = f"""# Project Zenith — Final Integration Test Report

## Status Summary

| Metric | Status |
| --- | --- |
| **Suite Outcome** | **{status_banner}** |
| **Execution Date** | {time.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Duration** | {duration:.2f} seconds |
| **Summary Details** | `{summary_line if summary_line else "See logs below"}` |

> {status_desc}

---

## 🛠️ Scope of Coverage

The test suite validates all primary components of the Project Zenith backend platform:

1. **Flask API Endpoints**: Verified health check endpoints, celestial coordinates, satellite searches, disaster listings, AI assistant chat, and ML predictions routing.
2. **Services**: Mapped SatelliteService (TLE download fallback), CelestialService, OrbitService, DisasterService, HotspotService, CollisionService, AnalyticsService, and AIService.
3. **ML Prediction Models**: Validated thread-safe caching via `ModelManager` and prediction outputs for all 6 serialized PKL models (Anomaly, Hotspot, Satellite Risk, Congestion, Disaster, Collision).
4. **PostgreSQL & Database Schema**: Configured and executed CRUD operations for all schema models (`User`, `Satellite`, `DisasterEvent`, `Hotspot`, `PredictionLog`, `OrbitalPrediction`, etc.) using an in-memory SQLite mapping.
5. **Redis Cache fallback**: Evaluated get/set, TTL, parameter-based MD5 hashing, and cache health checking.
6. **APScheduler**: Checked background job loops defensively.
7. **Mission Assistant chatbot**: Evaluated routing pattern queries (satellites, disasters, collision, space weather) and contextual response quality.

---

## 📋 Full Test Suite Execution Logs

```text
{pytest_output}
```

{errors_section}

---
Report auto-generated by `tests/generate_report.py`.
"""

    # Save the report in the workspace root as well as in the brain artifacts folder if available
    workspace_report_path = "integration_test_report.md"
    with open(workspace_report_path, "w") as f:
        f.write(report_content)
    print(f"Saved integration report to {workspace_report_path}")

    brain_dir = "/Users/sohamshaw/.gemini/antigravity-ide/brain/a0c6efe3-86fd-4bfa-a762-32a3d578a6cb"
    if os.path.exists(brain_dir):
        brain_report_path = os.path.join(brain_dir, "integration_test_report.md")
        with open(brain_report_path, "w") as f:
            f.write(report_content)
        print(f"Saved integration report copy to artifact directory: {brain_report_path}")

    return exit_code

if __name__ == "__main__":
    exit_code = run_suite_and_generate_report()
    sys.exit(exit_code)
